"""empty message

Revision ID: 141fe7d68cb4
Revises: 797527a05e23
Create Date: 2017-06-24 22:04:51.878219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '141fe7d68cb4'
down_revision = '797527a05e23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_uid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['create_uid'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('create_uid')

    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
