"""empty message

Revision ID: 40e6d404f941
Revises: 75aeacf0141e
Create Date: 2017-06-23 18:04:43.094357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40e6d404f941'
down_revision = '75aeacf0141e'
branch_labels = None
depends_on = None


def upgrade():
    # Commands auto generated by Alembic - please adjust!
    with op.batch_alter_table("polls") as batch_op:
        batch_op.drop_column('status')
    op.add_column('topics', sa.Column('status', sa.Boolean(), default=1))
    # ### end Alembic commands ###


def downgrade():
    # Commands auto generated by Alembic - please adjust!
    with op.batch_alter_table("topics") as batch_op:
        batch_op.drop_column('status')
    op.add_column('polls', sa.Column('status', sa.BOOLEAN(), nullable=True))
    # End Alembic commands

